TRUTHS_KIDS = [
  "If your pet could report you to your parents, what would it say?",
  "If you were a vegetable, which one would you be?",
  "If your teacher became your student for one day, what would you teach?",
  "What would you do if your shoes started talking?",
  "If your backpack could speak, what would it complain about?",
  "Which animal would be the worst bus driver?",
  "If you could replace your school bell with any sound, what would it be?",
  "If you had to eat only one snack for a year, what would it be?",
  "Which cartoon character would make the funniest principal?",
  "If your pillow could tell stories, what would it say?",
  "What would name a purple elephant?",
  "If you had a chicken as a best friend, what would you do together?",
  "Which fruit would win a dance competition?",
  "If your socks had feelings, what would they say?",
  "What is the funniest face you can make?",
  "If pencils could sing, what song would they sing?",
  "If your school had a swimming pool on the roof, would you use it?",
  "If you could only walk backward for one day, would you try?",
  "What would you do if your lunch started talking?",
  "Which superhero would be terrible at hiding?",
  "If your teacher had to wear a superhero costume every day, which one should they wear?",
  "If your shadow could leave you, where would it go?",
  "Which animal laughs the funniest?",
  "If bananas could talk, what would they say?",
  "What would happen if monkeys became teachers?",
  "If your alarm clock could chase you, would you run?",
  "Which emoji looks most like you in the morning?",
  "If you became invisible for five minutes, what funny thing would you do?",
  "Which animal would be the funniest chef?",
  "If your favorite snack could talk, what would it tell you?",
  "If your bed had wheels, where would you take it?",
  "If clouds were made of food, what food should they be?",
  "What would you do if your toothbrush disappeared every morning?",
  "If your school bag had a secret, what would it be?",
  "Which animal would make the funniest doctor?",
  "If your teacher laughed like a duck, what would you do?",
  "If you could wear pajamas to school forever, would you?",
  "If you had spaghetti for hair, what hairstyle would you choose?",
  "Which animal would make the funniest singer?",
  "What would you do if your chair started dancing?",
  "If your shoes could choose where to go, where would they take you?",
  "If you could talk like a robot for one day, would you?",
  "Which animal would be the funniest class monitor?",
  "If you had a dinosaur as a pet, what would you name it?",
  "If your homework could do itself, what would it say?",
  "Which food would make the funniest superhero?",
  "If you had a magic banana, what would it do?",
  "If your nose made a different sound every time you sneezed, what sound would you choose?",
  "Which animal would win a comedy show?",
  "If you had to wear clown shoes for a week, would you?"
]

TRUTHS_ADULTS = [
  "If your phone could expose one of your habits, what would it say?",
  "What is your 'I hope nobody saw that' moment?",
  "If your life had background music, what song would play when you enter a room?",
  "Which emoji is your real personality?",
  "If your boss became your assistant for a day, what would you ask them to do?",
  "If your fridge could talk, what would it complain about?",
  "Which friend would survive a zombie attack by hiding behind everyone else?",
  "If your search history became a movie, what would its title be?",
  "What would your pet say if it could review you online?",
  "If you had to wear only one color forever, which would you choose?",
  "Which app would miss you the most if you deleted it?",
  "If your bed had feelings, what would it think about you?",
  "What is the funniest excuse you have ever made in your head?",
  "If your wallet could speak, what would it say?",
  "Which food best matches your personality?",
  "If your laugh had a name, what would it be?",
  "Which cartoon character would make the worst roommate?",
  "If coffee disappeared forever, how would you survive?",
  "If you had to marry your favorite snack, what would it be?",
  "If your pillow wrote a diary about you, what would the first page say?",
  "Which animal would make the funniest office manager?",
  "If your life became a meme, what would it be?",
  "What would your mirror say if it could talk?",
  "If you had to replace your name with a food name, what would it be?",
  "Which movie character would be terrible at using a smartphone?",
  "If your shoes kept a secret about you, what would it be?",
  "What is the funniest thing you believed as a child?",
  "If your car or bike could complain, what would it say?",
  "If your family made a reality show, what would it be called?",
  "Which vegetable has the biggest attitude?",
  "If you woke up as a chicken, what is the first thing you would do?",
  "If you had a robot, what lazy job would you give it?",
  "Which fruit would be the funniest stand-up comedian?",
  "If your life had bloopers, which one would be the funniest?",
  "What would your future self laugh at today?",
  "If you had to wear a superhero cape every day, what color would it be?",
  "Which animal would be the funniest neighbor?",
  "If your phone battery had feelings, what would it say?",
  "If you had to speak only in movie quotes for one day, could you do it?",
  "Which friend would accidentally become famous?",
  "If your favorite food could judge you, what would it say?",
  "If your slippers could run away, where would they go?",
  "Which emoji should become a real person?",
  "If your Wi-Fi could talk, what would it complain about?",
  "If you became a cartoon for one day, what would you do first?",
  "What would your shopping cart say about you?",
  "If your hairstyle had its own personality, what would it be like?",
  "Which animal would make the funniest politician?",
  "If your dreams were made into a comedy show, what would the title be?",
  "If everyone had to wear costumes every Friday, what costume would you choose?"
]

DARES_KIDS = [
  "Walk like a penguin for 30 seconds.",
  "Talk like a robot for one minute.",
  "Pretend to be a chicken until your next turn.",
  "Dance like nobody is watching for 20 seconds.",
  "Hop on one foot around the room.",
  "Make your funniest face and hold it for 10 seconds.",
  "Pretend to brush your teeth with your finger.",
  "Act like a sleepy cat.",
  "Say the alphabet like a superhero.",
  "Walk like a dinosaur.",
  "Pretend to be a monkey eating a banana.",
  "Sing 'Happy Birthday' like an opera singer.",
  "Act like you are swimming on the floor.",
  "Pretend your shoes are too hot to wear.",
  "Talk without using the letter 'S' for one minute.",
  "Walk in slow motion until your next turn.",
  "Pretend to be a news reporter talking about a banana.",
  "Do your best lion roar.",
  "Pretend to be a baby asking for ice cream.",
  "Balance a book on your head for 20 seconds.",
  "Pretend you are a famous movie star.",
  "Laugh like Santa Claus.",
  "Act like a superhero looking for your cape.",
  "Pretend to ride an invisible horse.",
  "Wiggle like a worm.",
  "Say your name in a cartoon voice.",
  "Pretend to be a fish out of water.",
  "Walk like a crab.",
  "Pretend to fly like a bird around the room.",
  "Do five funny dance moves.",
  "Pretend to be a sleepy panda.",
  "Count from 1 to 20 like a duck.",
  "Pretend to be a washing machine.",
  "Make three funny animal sounds.",
  "Act like a magician performing a trick.",
  "Pretend to eat invisible spaghetti.",
  "Walk with tiny baby steps.",
  "Pretend to be a robot that needs charging.",
  "Say 'I love pizza!' in five different voices.",
  "Act like you are stuck in jelly.",
  "Pretend to blow up a giant balloon.",
  "Smile without laughing for 30 seconds.",
  "Pretend to climb an invisible ladder.",
  "Dance like a happy elephant.",
  "Act like you won the world's funniest award.",
  "Pretend to be a clock ticking.",
  "Speak like a pirate for one minute.",
  "Pretend your backpack is your best friend.",
  "Wave to everyone like a king or queen.",
  "End your dare with a superhero pose."
]

DARES_ADULTS = [
  "Speak like a news anchor for one minute.",
  "Pretend to sell an invisible product.",
  "Walk like a runway model across the room.",
  "Give a weather report for another planet.",
  "Dance for 20 seconds with no music.",
  "Pretend you are a famous chef explaining how to cook water.",
  "Laugh like a movie villain.",
  "Act like your phone is your best friend.",
  "Pretend to answer an imaginary phone call from an alien.",
  "Speak only in questions until your next turn.",
  "Do your best robot dance.",
  "Pretend you are a tour guide in your own house.",
  "Act like a slow-motion superhero.",
  "Pretend to teach a class about socks.",
  "Give an acceptance speech for winning 'Best Napper.'",
  "Walk like you're on the moon.",
  "Pretend to be a GPS giving directions to the refrigerator.",
  "Make up a funny TV commercial for toothpaste.",
  "Act like a cat trying to use a computer.",
  "Pretend you're a detective solving the mystery of the missing cookie.",
  "Read the next sentence in your funniest voice.",
  "Pretend you're a flight attendant explaining silly safety rules.",
  "Sing your favorite song like an opera singer.",
  "Pretend you're a waiter serving invisible food.",
  "Do your best chicken dance.",
  "Act like you're stuck in slow motion.",
  "Pretend to be a superhero whose only power is making sandwiches.",
  "Walk around as if the floor is made of LEGO bricks.",
  "Describe your day like a sports commentator.",
  "Pretend to interview yourself on a talk show.",
  "Do your best dinosaur impression.",
  "Smile without laughing for one minute.",
  "Pretend you're a washing machine on the spin cycle.",
  "Introduce everyone as if they are movie stars.",
  "Pretend to be a statue until someone says your name.",
  "Narrate everything you do for one minute.",
  "Act like you're trying to open a door that doesn't exist.",
  "Pretend you're a magician whose tricks never work.",
  "Dance like a happy penguin.",
  "Tell a joke using three random words chosen by the group.",
  "Pretend to ride an invisible bicycle.",
  "Act like you're walking through strong wind.",
  "Say the alphabet with a different emotion for each letter.",
  "Pretend to be a game show host.",
  "Give a motivational speech to a water bottle.",
  "Act like a sleepy sloth.",
  "Pretend your shoe is a microphone and sing into it.",
  "Explain how to eat a banana like a science teacher.",
  "End your turn with your funniest superhero pose.",
  "Create a new dance move and give it a funny name."
]
